---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgressql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgressql
    spec:
      containers:
        - name: postgressql
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name:  POSTGRES_PASSWORD
              value: postgres
  selector:
    matchLabels:
      app: postgressql
---
apiVersion: v1
kind: Service
metadata:
  name: postgressql
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgressql    
